//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int32_t unknown_400780(int32_t a1, int32_t a2, int32_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x400edc - 0x4013bb
int main(int argc, char ** argv) {
    // 0x400edc
    int32_t v1;
    int32_t v2 = v1; // bp-24
    int32_t v3;
    int32_t fd = v3; // bp-20
    int32_t v4;
    int32_t mem = v4; // bp-16
    int32_t v5;
    int32_t mem2 = v5; // bp-12
    int32_t v6;
    int32_t v7 = v6; // bp-8
    int32_t v8;
    int32_t v9 = v8; // bp-4
    int32_t v10;
    int32_t v11 = v10;
    int32_t v12;
    char ** v13 = (char **)v12;
    v9 = 0;
    v7 = 0;
    v11 = argc;
    v13 = argv;
    v2 = 0;
    int32_t result;
    if (v11 == 2) {
        // 0x400f34
        v11--;
        int32_t path = (int32_t)v13 + 4; // 0x400f44
        v13 = (char **)path;
        fd = open((char *)*(int32_t *)path, O_RDONLY);
        if (fd > -1) {
            // 0x400f80
            mem = (int32_t)malloc(40);
            if (mem == 0) {
                // 0x4013a4
                return -1;
            }
            // 0x400fa8
            mem2 = (int32_t)malloc(80);
            if (mem2 != 0) {
                // 0x400fd0
                memset((char *)mem, 0, 40);
                memset((char *)mem2, 0, 80);
                v2 = read(fd, (char *)mem, 24);
                if (v2 > 0) {
                    // 0x401040
                    *(char *)(mem + v2) = 0;
                    close(fd);
                    unknown_400780(mem2, mem, 24);
                    if (*(char *)mem2 == 101) {
                        // 0x401080
                        if (*(char *)(mem2 + 1) == 81) {
                            // 0x401098
                            if (*(char *)(mem2 + 2) == 52) {
                                // 0x4010b0
                                if (*(char *)(mem2 + 3) == 121) {
                                    // 0x4010c8
                                    if (*(char *)(mem2 + 4) == 52) {
                                        // 0x4010e0
                                        if (*(char *)(mem2 + 5) == 54) {
                                            // 0x4010f8
                                            if (*(char *)(mem2 + 6) == 43) {
                                                // 0x401110
                                                if (*(char *)(mem2 + 7) == 86) {
                                                    // 0x401128
                                                    if (*(char *)(mem2 + 8) == 117) {
                                                        // 0x401140
                                                        if (*(char *)(mem2 + 9) == 102) {
                                                            // 0x401158
                                                            if (*(char *)(mem2 + 10) == 90) {
                                                                // 0x401170
                                                                if (*(char *)(mem2 + 11) == 122) {
                                                                    // 0x401188
                                                                    if (*(char *)(mem2 + 12) == 100) {
                                                                        // 0x4011a0
                                                                        if (*(char *)(mem2 + 13) == 70) {
                                                                            // 0x4011b8
                                                                            if (*(char *)(mem2 + 14) == 78) {
                                                                                // 0x4011d0
                                                                                if (*(char *)(mem2 + 15) == 70) {
                                                                                    // 0x4011e8
                                                                                    if (*(char *)(mem2 + 16) == 100) {
                                                                                        // 0x401200
                                                                                        if (*(char *)(mem2 + 17) == 120) {
                                                                                            // 0x401218
                                                                                            if (*(char *)(mem2 + 18) == 48) {
                                                                                                // 0x401230
                                                                                                if (*(char *)(mem2 + 19) == 122) {
                                                                                                    // 0x401248
                                                                                                    if (*(char *)(mem2 + 20) == 117) {
                                                                                                        // 0x401260
                                                                                                        if (*(char *)(mem2 + 21) == 100) {
                                                                                                            // 0x401278
                                                                                                            if (*(char *)(mem2 + 22) == 115) {
                                                                                                                // 0x401290
                                                                                                                if (*(char *)(mem2 + 23) == 97) {
                                                                                                                    // 0x4012a8
                                                                                                                    if (*(char *)(mem2 + 24) == 43) {
                                                                                                                        // 0x4012c0
                                                                                                                        if (*(char *)(mem2 + 25) == 121) {
                                                                                                                            // 0x4012d8
                                                                                                                            if (*(char *)(mem2 + 26) == 89) {
                                                                                                                                // 0x4012f0
                                                                                                                                if (*(char *)(mem2 + 27) == 48) {
                                                                                                                                    // 0x401308
                                                                                                                                    if (*(char *)(mem2 + 28) == 43) {
                                                                                                                                        // 0x401320
                                                                                                                                        if (*(char *)(mem2 + 29) == 74) {
                                                                                                                                            // 0x401338
                                                                                                                                            if (*(char *)(mem2 + 30) == 50) {
                                                                                                                                                // 0x401350
                                                                                                                                                if (*(char *)(mem2 + 31) == 109) {
                                                                                                                                                    // 0x401388
                                                                                                                                                    printf("flag is : %s\n", (char *)mem);
                                                                                                                                                    // branch -> 0x4013a4
                                                                                                                                                    // 0x4013a4
                                                                                                                                                    return 0;
                                                                                                                                                }
                                                                                                                                            }
                                                                                                                                        }
                                                                                                                                    }
                                                                                                                                }
                                                                                                                            }
                                                                                                                        }
                                                                                                                    }
                                                                                                                }
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    // 0x40136c
                    puts("wrong!");
                    // branch -> 0x4013a4
                }
            }
            // 0x4013a4
            return -1;
        }
        result = -1;
    } else {
        // 0x400f04
        printf("usage: %s flag.txt\n", (char *)*(int32_t *)v13);
        result = 0;
        // branch -> 0x4013a4
    }
    // 0x4013a4
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int close(int fd);
// void * malloc(size_t size);
// void * memset(void * s, int c, size_t n);
// int open(const char * file, int oflag, ...);
// int printf(const char * restrict format, ...);
// int puts(const char * s);
// ssize_t read(int fd, void * buf, size_t nbytes);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.6.3)
// Detected functions: 1
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2018-05-26 04:15:36
