//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t function_400b24(int32_t argc, int32_t * argv, int32_t a3);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // 0x410798

// ------------------------ Functions -------------------------

// Address range: 0x400b24 - 0x400d33
int32_t main(int32_t argc, int32_t * argv, int32_t a3) {
    // 0x400b24
    int32_t v1;
    int32_t v2 = v1; // bp-288
    int32_t v3 = (int32_t)argv;
    int32_t v4 = v3; // $argc
    int32_t v5 = a3; // $argv
    int32_t result; // 0x400d2c_1
    if (argc >= 2) {
        int32_t v6 = *(int32_t *)(v3 + 4); // 0x400b90
        if (function_402b20(v6) == 32) {
            int32_t v7 = 0;
            // branch -> 0x400bdc
            while (true) {
                int32_t v8 = function_400a04(v7 + v6, v4, v5, 0); // 0x400bec
                v2 = 0;
                int32_t v9;
                int32_t v10 = 8 * v7 + (int32_t)&v9; // 0x400c18
                v5 = v10;
                v4 = 12;
                function_400520(v8, 12, v10, 0, 0x42a3f0);
                int32_t v11 = 1; // 0x400c38
                v2 = v11;
                // branch -> 0x400c08
                while (v11 < 0xf4240) {
                    // 0x400c08
                    v5 = v10;
                    v4 = 12;
                    function_400520(v8, 12, v10, 0, 0x42a3f0);
                    v11++;
                    v2 = v11;
                    // continue -> 0x400c08
                }
                int32_t v12 = v7 + 2; // 0x400c5c
                if (v12 >= 32) {
                    // break -> 0x400cec
                    break;
                }
                v7 = v12;
                // continue -> 0x400bdc
            }
            int32_t v13 = (int32_t)&v2 + 24; // 0x400c94
            int32_t v14 = 0;
            // branch -> 0x400cd0
            int32_t v15; // 0x400ca0
            while (true) {
                // 0x400cd0
                v2 = 0;
                int32_t v16 = 0; // 0x400cb8
                v15 = (int32_t)*(char *)(v13 + v14 + v16);
                function_400e90((int32_t)"%2.2x", v15, v5, 0, 0x42a3f0, 0, v16, 32, v14);
                int32_t v17 = v2 + 1; // 0x400cc8
                v2 = v17;
                // branch -> 0x400c8c
                while (v17 < 16) {
                    // 0x400c8c
                    v16 = v17;
                    v15 = (int32_t)*(char *)(v13 + v14 + v16);
                    function_400e90((int32_t)"%2.2x", v15, v5, 0, 0x42a3f0, 0, v16, 32, v14);
                    v17 = v2 + 1;
                    v2 = v17;
                    // continue -> 0x400c8c
                }
                int32_t v18 = v14 + 16; // 0x400ce4
                if (v18 >= 256) {
                    // break -> 0x400cf8
                    break;
                }
                v14 = v18;
                // continue -> 0x400cd0
            }
            // 0x400cf8
            function_400d40((int32_t)&g1, v15, v5, 0, 0, 0, 0, 0, 0, 0);
            result = 0;
            // branch -> 0x400d1c
        } else {
            result = 0;
        }
    } else {
        int32_t v19 = *argv; // 0x400b5c
        int32_t v20;
        int32_t v21;
        function_400e90((int32_t)"usage: %s 'flag'\n", v19, a3, 0, 0x42a3f0, 0, v1, v21, v20);
        result = 1;
        // branch -> 0x400d1c
    }
    // 0x400d1c
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (5.4.0)
// Detected functions: 1
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2018-03-14 12:40:31
